### PR TITLE
.github/workflows: update workflow target branch

### LINKED ISSUE #76: Github actions for go-dap are broken
The workflow has not been run for 2 years as can be seen on the Actions tab and the tests are not being run on incoming PRs. It appears this is due to the name change of the default branch from master -> main.

### PR DESCRIPTION
**Pull request by suzmue**
The default branch for google/go-dap is now main. Also update the go versions and the github action versions.

Fixes #76

### CODE REVIEW

File: internal/test.sh [hunk 1]
```diff
@@ -7,14 +7,15 @@ if [[ $# -gt 0 ]]; then
...
+# at latest.
 ensure_go_binary() {
   local binary=$(basename $1)
   if ! [ -x "$(command -v $binary)" ]; then
-    info "Installing: $1"
+    echo "Installing: $1"
     # Run in a subshell for convenience, so that we don't have to worry about
     # our PWD.
-    (set -x; cd && env GO111MODULE=on go get -u $1)
+    (set -x; cd && env GO111MODULE=on go install $1@latest)
```
Comment (hyangah) [inline internal/test.sh:18]: I think just `go install $1@latest` is sufficient - GO111MODULE is default now.

(optional) it seems that we just need staticcheck test in addition to go test ./... and this shell isn't very useful.
We can consider to replace staticcheck with https://staticcheck.io/docs/running-staticcheck/ci/github-actions/ or clone of it, and get rid of this bash script completely and make this workflow work on windows too.

**Review by hyangah — APPROVED** [review]

File: internal/test.sh (hunk 1 above)
Comment (suzmue) [reply internal/test.sh]: Agreed. I'll send a follow up for updating the staticcheck #78

**Review by pjweinb — APPROVED** [review]
